In [1]:
import numpy as np

arr1 = np.array([10, 20, 30, 40, 50])
arr2 = np.linspace(0, 100, 11)
arr3 = np.random.randint(1, 100, size=(4, 4))

identity = np.eye(4)

print("1D Array:\n", arr1)
print("\nLinspace Array:\n", arr2)
print("\nRandom Matrix:\n", arr3)
print("\nIdentity Matrix:\n", identity)

1D Array:
 [10 20 30 40 50]

Linspace Array:
 [  0.  10.  20.  30.  40.  50.  60.  70.  80.  90. 100.]

Random Matrix:
 [[12 56 73 80]
 [51 30 50 42]
 [59 27 38 69]
 [77 48 43 66]]

Identity Matrix:
 [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [2]:
import numpy as np
matrix = np.random.randint(1, 100, (5,5))

print("Original Matrix:\n")
print(matrix)

print("\nElement at Row 2, Column 3:")
print(matrix[1,2])

print("\nSubmatrix:")
print(matrix[1:4,1:4])

print("\nValues Greater Than 50:")
print(matrix[matrix > 50])

Original Matrix:

[[92 13 23 90 70]
 [33 71 49 75 45]
 [63 99 49  2 91]
 [34 75  5 55 96]
 [41 76 31  4 14]]

Element at Row 2, Column 3:
49

Submatrix:
[[71 49 75]
 [99 49  2]
 [75  5 55]]

Values Greater Than 50:
[92 90 70 71 75 63 99 91 75 55 96 76]


In [3]:
import numpy as np

data = np.random.randint(10, 100, 20)

print("Dataset:")
print(data)

print("\nMean:", np.mean(data))
print("Median:", np.median(data))
print("Standard Deviation:", np.std(data))
print("Variance:", np.var(data))
print("Maximum Value:", np.max(data))
print("Minimum Value:", np.min(data))

Dataset:
[22 96 43 57 23 33 69 47 96 62 16 83 72 11 55 76 63 66 64 98]

Mean: 57.6
Median: 62.5
Standard Deviation: 25.852272627372624
Variance: 668.3399999999999
Maximum Value: 98
Minimum Value: 11


In [4]:
import numpy as np
A = np.array([[2,4],[3,5]])
B = np.array([[1,2],[3,4]])

print("Matrix A:\n",A)
print("\nMatrix B:\n",B)

print("\nAddition:")
print(A + B)

print("\nMultiplication:")
print(np.dot(A,B))

print("\nDeterminant of A:")
print(np.linalg.det(A))

print("\nInverse of A:")
print(np.linalg.inv(A))

print("\nEigen Values:")
print(np.linalg.eig(A)[0])

Matrix A:
 [[2 4]
 [3 5]]

Matrix B:
 [[1 2]
 [3 4]]

Addition:
[[3 6]
 [6 9]]

Multiplication:
[[14 20]
 [18 26]]

Determinant of A:
-2.000000000000001

Inverse of A:
[[-2.5  2. ]
 [ 1.5 -1. ]]

Eigen Values:
[-0.27491722  7.27491722]
